---
# Variable configuration.
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true

- name: Define prerequisite packages
  set_fact:
    prerequisite_packages: "{{ __prerequisite_packages | list }}"
  when: prerequisite_packages is not defined
